server:
  port: 80


spring:
  application:
    name: cloud-order-service

eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    #    service-url:
    #      defaultZone: http://localhost:7001/eureka  #单机版
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版



ribbon:
  #指的是室立连接后从服务器读取到可用资源所用的时间f
  ReadTimeout:  5000
  #没置feign客户髋超旳时ri( openFeign.默认支持ribbor)
  ConnectTimeout: 5000

# 开启feign日志
logging:
  level:
    com.atguigu.springcloud.service.PaymentFeignService: debug



