server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # 开启从注册中心动态创建路由的功能，利用微服务名称进行路由
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/getPaymentById/**   #断言,路径相匹配的进行路由

        - id: payment_routh2
#          uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVICE
#          filters:
#            - AddRequestParameter=X-Request-Id,1024 #过滤器工厂会在匹配的请求头加上一对请求头，名称为X-Request-Id值为1024
          predicates:
            - Path=/payment/lb/**   #断言,路径相匹配的进行路由
#            - After=2020-08-12T16:44:15.064+08:00[Asia/Shanghai]  #表示该路由在该时间之后才能执行
#            - Before=2050-03-08T10:59:34.102+08:00[Asia/Shanghai] #表示该路由在该时间之前才能执行
#            - Between=2020-03-08T10:59:34.102+08:00[Asia/Shanghai],2050-03-08T10:59:34.102+08:00[Asia/Shanghai] #表示该路由在该时间之间才能执行
#            - Cookie=username,eiletxie   #带Cookie，并且username的值为eiletxie
#            - Header=X-Request-Id,\d+ #请求头要有 X-Request-Id属性并且值为整数的正则表达式
#            - Host=**.hyd.com
#            - Method=GET
#            - Query=username, \d+ #要有参数名称并且是正整数才能路由

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka


